[workspace]
members = [
    "injector",
    "encryption/encryption",
    "encryption/encryption-procmacro",
    "cstruct",
    "schema",
    "sdk",
    "moros",
]

[profile.release]
debug = false
strip = true
